# 修改 /etc/kubernetes/manifests/kube-apiserver.yaml, 把 client-ca-file 的 ca_authurity.crt 换成 ca_crt
# 由于这个是 static pod 所以，修改后会自动生效
# 修改 ~/.kube/config 中的端口为 6443
# 修改 corends 的镜像
---
# kubectl uncordon node01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /web

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: data-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: fileserver
spec:
  containers:
  - name: gop-fileserver
    image: kodekloud/fileserver
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /web
      name: data-store
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    app: fileserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
---
# 31200 端口验证